ALJEproject/ALJEproject/Controllers/MenuController.cs
using ALJEproject.Data;
using ALJEproject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using ClosedXML.Excel;
using System.IO;
using ALJEproject.Services.Interfaces;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;

namespace ALJEproject.Controllers
{
    public class MenuController : Controller
    {
        private readonly ILogger<MenuController> _logger;
        private readonly ALJEprojectDbContext _context;
        private readonly IUserService _userService;

        // Constructor that combines both dependencies
        public MenuController(IUserService userService, ALJEprojectDbContext context, ILogger<MenuController> logger)
        {
            _context = context;
            _logger = logger;
            _userService = userService;
        }

        // GET: Menu
        public async Task<IActionResult> Index(string search, int page = 1, int pageSize = 10)
        {

            IEnumerable<Menu> menus;
            int totalMenus;

            if (!string.IsNullOrWhiteSpace(search))
            {
                menus = _userService.SearchMenus(search, page, pageSize);
                totalMenus = _userService.GetTotalMenusCount(search);
            }
            else
            {
                menus = _userService.GetPaginatedMenus(page, pageSize);
                totalMenus = _userService.GetTotalMenusCount();
            }

            var model = new PaginatedMenuViewModel
            {
                Menus = menus,
                CurrentPage = page,
                PageSize = pageSize,
                TotalCount = totalMenus
            };

            ViewData["CurrentSearch"] = search;

            return View(model);
        }



        // GET: Menu/Create
        [HttpGet]
        public IActionResult Create()
        {
            var parentMenus = _context.Menus
            .Where(m => m.Active && m.ParentMenuID==null) // Hanya ambil menu yang aktif (opsional)
            .Select(r => new ParentMenuItem { MenuID = r.MenuID, MenuDesc = r.MenuName }) // Map ke model khusus
            .ToList();

            // Tambahkan opsi 'Parent' dengan nilai NULL
            parentMenus.Insert(0, new ParentMenuItem { MenuID = null, MenuDesc = "Set Parent" });

            ViewBag.ParentMenus = new SelectList(parentMenus, "MenuID", "MenuDesc");

            return PartialView("_CreateMenuPartial");
        }

        // POST: Menu/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Menu menu)
        {

            if (ModelState.IsValid)
            {
                string createdBy = HttpContext.Session.GetString("Username");
                menu.CreatedDate = DateTime.Now;
                menu.CreatedBy = createdBy; // Set as appropriate, e.g., logged-in user
                _context.Menus.Add(menu);
                _context.SaveChanges();
                return Json(new { success = true });
            }

            var parentMenus = _context.Menus.Select(r => new { r.ParentMenuID, r.MenuName }).ToList();
            ViewBag.ParentMenus = new SelectList(parentMenus, "MenuID", "MenuDesc");

            return Json(new { success = false, errors = ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage)).ToList() });
        }

        // GET: Menu/Edit/5
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var menu = _context.Menus.Find(id);
            if (menu == null)
            {
                return NotFound();
            }

            return PartialView("_EditMenuPartial", menu);
        }

        // POST: Menu/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Menu menu)
        {
            if (ModelState.IsValid)
            {
                string updateBy = HttpContext.Session.GetString("Username");
                try
                {
                    menu.UpdatedDate = DateTime.Now;
                    menu.UpdatedBy = updateBy; // Set as appropriate, e.g., logged-in user
                    _context.Update(menu);
                    _context.SaveChanges();
                    _logger.LogInformation("Menu with ID {MenuId} updated successfully.", menu.MenuID);
                    return Json(new { success = true });
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "An error occurred while updating menu with ID {MenuId}.", menu.MenuID);
                    return Json(new { success = false, message = "An error occurred while updating the menu." });
                }
            }

            var errorMessages = ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage)).ToList();
            _logger.LogError("Failed to update menu with ID {MenuId}. Model state is invalid.", menu.MenuID);

            return Json(new { success = false, errors = errorMessages });
        }

        // POST: Menu/Delete/5
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var menu = _context.Menus.Find(id);
            if (menu != null)
            {
                _context.Menus.Remove(menu);
                _context.SaveChanges();
                _logger.LogInformation("Menu with ID {MenuId} deleted successfully.", id);
                return Json(new { success = true });
            }
            return Json(new { success = false, errors = new[] { "Menu not found." } });
        }

        public IActionResult View(int id)
        {
            var menu = _context.Menus.FirstOrDefault(u => u.MenuID == id);
            if (menu == null)
            {
                return NotFound();
            }
            return PartialView("_ViewMenuPartial", menu); // Use a partial view for the modal content
        }

        public IActionResult ExportToExcel()
        {
            // Assuming you have a method to get option data
            var menus = _context.Menus.ToList();

            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("menus");
                worksheet.Cell(1, 1).Value = "MenuID";
                worksheet.Cell(1, 2).Value = "MenuName";
                worksheet.Cell(1, 3).Value = "MenuURL";
                worksheet.Cell(1, 4).Value = "ControllerName";
                worksheet.Cell(1, 5).Value = "CreatedBy";
                worksheet.Cell(1, 6).Value = "UpdatedBy";

                for (int i = 0; i < menus.Count; i++)
                {
                    worksheet.Cell(i + 2, 1).Value = menus[i].MenuID;
                    worksheet.Cell(i + 2, 2).Value = menus[i].MenuName;
                    worksheet.Cell(i + 2, 3).Value = menus[i].MenuURL;
                    worksheet.Cell(i + 2, 4).Value = menus[i].ControllerName;
                    worksheet.Cell(i + 2, 5).Value = menus[i].CreatedBy;
                    worksheet.Cell(i + 2, 6).Value = menus[i].UpdatedBy;
                }

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ListMenu.xlsx");
                }
            }
        }
    }
}

ALJEproject/ALJEproject/Controllers/RoleController.cs
using ALJEproject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;
using ALJEproject.Data;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System;
using ALJEproject.Services.Interfaces;
using System.Collections.Generic;
using ClosedXML.Excel;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace ALJEproject.Controllers
{
    public class RoleController : Controller
    {
        private readonly ILogger<RoleController> _logger;
        private readonly ALJEprojectDbContext _context;
        private readonly IUserService _userService;

        // Konstruktor yang menggabungkan kedua dependensi
        public RoleController(IUserService userService, ALJEprojectDbContext context, ILogger<RoleController> logger)
        {
            _context = context;
            _logger = logger;
            _userService = userService;
        }

        public async Task<IActionResult> Index(string search, int page = 1, int pageSize = 10)
        {
            var menus = await _userService.GetActiveMenusAsync();
            ViewBag.Menus = menus;
            IEnumerable<RoleView> roles; // Assuming you have a RoleViewModel
            int totalRoles; // Declare a variable for total role count

            if (!string.IsNullOrWhiteSpace(search))
            {
                roles = _userService.SearchRoles(search, page, pageSize);
                // Get the total count of roles matching the search criteria
                totalRoles = _userService.GetTotalRolesCount(search); // Pass the search term to count matching roles
            }
            else
            {
                roles = _userService.GetPaginatedRoles(page, pageSize);
                totalRoles = _userService.GetTotalRolesCount(); // Get the total role count without filtering
            }

            var model = new PaginatedRoleViewModel
            {
                Roles = roles,
                CurrentPage = page,
                PageSize = pageSize,
                TotalCount = totalRoles // This will now reflect the correct count based on search
            };

            ViewData["CurrentSearch"] = search; // Save search term to display in the view

            return View(model);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return PartialView("_CreateRolePartial");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Role role)
        {
            if (ModelState.IsValid)
            {
                string createdBy = HttpContext.Session.GetString("Username");
                role.CreatedDate = DateTime.Now;
                role.CreatedBy = createdBy; // Atur CreatedBy dari user yang sedang login
                _context.Roles.Add(role);
                _context.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false, errors = ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage)) });
        }

        // GET: Role/Edit/5
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var role = _context.Roles.Find(id);
            if (role == null)
            {
                return NotFound();
            }
            return PartialView("_EditRolePartial", role);
        }

        // POST: Role/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Role role)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string updateBy = HttpContext.Session.GetString("Username");
                    role.UpdatedDate = DateTime.Now;
                    role.UpdatedBy = updateBy; // Atur UpdatedBy dari user yang sedang login
                    _context.Update(role);
                    _context.SaveChanges();
                    _logger.LogInformation("Role with ID {RoleId} updated successfully.", role.RoleID);
                    return Json(new { success = true });
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "An error occurred while updating role with ID {RoleId}.", role.RoleID);
                    return Json(new { success = false, message = "An error occurred while updating the role." });
                }
            }

            var errorMessages = ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage)).ToList();
            _logger.LogError("Failed to update role with ID {RoleId}. Model state is invalid.", role.RoleID);

            return Json(new { success = false, errors = errorMessages });
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var role = _context.Roles.Find(id);
            if (role != null)
            {
                _context.Roles.Remove(role);
                _context.SaveChanges();
                _logger.LogInformation("Role with ID {RoleId} deleted successfully.", id);
                return Json(new { success = true });
            }
            return Json(new { success = false, errors = new[] { "Role not found." } });
        }

        public IActionResult View(int id)
        {
            var role = _context.Roles.FirstOrDefault(u => u.RoleID == id);
            if (role == null)
            {
                return NotFound();
            }
            return PartialView("_ViewRolePartial", role); // Use a partial view for the modal content
        }

        public IActionResult ExportToExcel()
        {
            // Assuming you have a method to get option data
            var roles = _context.Roles.ToList();

            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("roles");
                worksheet.Cell(1, 1).Value = "RoleID";
                worksheet.Cell(1, 2).Value = "RoleName";
                worksheet.Cell(1, 3).Value = "CreatedBy";
                worksheet.Cell(1, 4).Value = "CreatedDate";
                worksheet.Cell(1, 5).Value = "UpdatedDate";
                worksheet.Cell(1, 6).Value = "UpdatedBy";

                for (int i = 0; i < roles.Count; i++)
                {
                    worksheet.Cell(i + 2, 1).Value = roles[i].RoleID;
                    worksheet.Cell(i + 2, 2).Value = roles[i].RoleName;
                    worksheet.Cell(i + 2, 3).Value = roles[i].CreatedBy;
                    worksheet.Cell(i + 2, 4).Value = roles[i].CreatedDate;
                    worksheet.Cell(i + 2, 5).Value = roles[i].UpdatedDate;
                    worksheet.Cell(i + 2, 6).Value = roles[i].UpdatedBy;
                }

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ListRole.xlsx");
                }
            }
        }

    }
}

ALJEproject/ALJEproject/Views/Shared/_Layout - Copy.cshtml
@using Microsoft.AspNetCore.Http
@{ 
    var username = Context.Session.GetString("Username"); // Ambil username dari session    
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ALJEproject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />

    <style>

        body {
            overflow-x: hidden;
        }

        #sidebar {
            min-height: 100vh;
            width: 250px;
            background-color: #4F709C;
            color: #fff;
            transition: all 0.3s;
        }

            #sidebar.collapsed {
                width: 60px;
            }

            #sidebar .menu-header {
                display: flex;
                align-items: center;
                justify-content: space-between;
                padding: 10px 15px;
                border-bottom: 1px solid #F5EFE7;
                /* background-color: #F5EFE7; */
            }

            #sidebar.collapsed .menu-item {
                display: none;
            }

        #content {
            transition: all 0.3s;
        }

            #content.collapsed {
            }

        #right-side {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            background-color: #D8C4B6;
            color: #fff;
            /* border-bottom: 1px solid #ddd; */
        }

        #user-info {
            display: flex;
            align-items: center;
        }

            #user-info img {
                width: 30px;
                height: 30px;
                border-radius: 50%;
                margin-right: 10px;
            }

        #sidebar.collapsed .menu-header h5 {
            display: none;
        }
        .footer {
            background-color: #F5EFE7;
            color: black;
            text-align: center;
            padding: 10px 0;
        }


    </style>

</head>
<body>
    <header>
        <div class="d-flex">
            <!-- Sidebar -->
            <nav id="sidebar">
                <div class="menu-header">
                    <button id="toggleSidebar" class="btn btn-primary btn-sm">
                        <i class="fas fa-bars"></i>
                    </button>
                    <h5 id="menuTitle" class="mb-0 text-white">My Menu</h5>
                </div>
                <ul class="nav flex-column p-2">
                    <li class="nav-item">
                        <a href="#" class="nav-link text-white">
                            <i class="fas fa-home"></i>
                            <span class="menu-item">Home</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link text-white">
                            <i class="fas fa-user"></i>
                            <span class="menu-item">Profile</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link text-white">
                            <i class="fas fa-cogs"></i>
                            <span class="menu-item">Settings</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link text-white">
                            <i class="fas fa-sign-out-alt"></i>
                            <span class="menu-item">Logout</span>
                        </a>
                    </li>
                </ul>
            </nav>

            <!-- Content -->
            <div id="content" class="flex-grow-1">
                <!-- Right-Side -->
                <div id="right-side">
                    <div>
                        <h6 class="mb-0">Alje Template</h6>
                    </div>
                    <div id="user-info">
                        <img src="https://via.placeholder.com/40" alt="User Image">
                        <span class="mr-3">John Doe</span>
                        <a href="#" class="btn btn-primary btn-sm">Logout</a>
                    </div>
                </div>

                <!-- Main Content -->
                <div class="p-4">
                    @RenderBody()
                </div>

                <!-- Footer -->
                <div class="footer mt-auto">
                    <p class="mb-1">&copy; @DateTime.Now.Year  - ALJEproject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>.</p>
                    <p class="small mb-0">
                        <a href="#" class="text-black-50 text-decoration-none">Privacy Policy</a> |
                        <a href="#" class="text-black-50 text-decoration-none">Terms of Service</a>
                    </p>
                </div>

            </div>



        </div>



        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ALJEproject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (ViewBag.Menus != null)
                        {
                            var groupedMenus = ViewBag.Menus as List<Menu>;

                            foreach (var parentMenu in groupedMenus.Where(m => m.ParentMenuID == null)) // Hanya ambil parent menu
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" id="menuDropdown_@parentMenu.MenuID" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @parentMenu.MenuDesc <!-- Nama parent menu sebagai label dropdown -->
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="menuDropdown_@parentMenu.MenuID">
                                        @foreach (var subMenu in parentMenu.SubMenus)
                                        {
                                            <a class="dropdown-item" asp-area="" asp-controller="@subMenu.ControllerName" asp-action="Index">@subMenu.MenuDesc</a>}
                                    </div>
                                </li>
                            }
                        }
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="administratorDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Administrator
                            </a>
                            <div class="dropdown-menu" aria-labelledby="administratorDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                                <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">User</a>
                                <a class="dropdown-item" asp-area="" asp-controller="UserAccess" asp-action="Index">User Access</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Option" asp-action="Index">Option</a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (!string.IsNullOrEmpty(username))
                        {
                            username = Context.Session.GetString("Username");
                            <li class="nav-item">
                                <span class="navbar-text text-dark">Hello, @username!</span>
                            </li>
                            <li class="nav-item">
                                <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="btn btn-link nav-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>

    



    </header>
    @*<div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year  - ALJEproject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/fontawesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        $(document).ready(function () {
            // Show side menu
            document.getElementById('toggleSidebar').addEventListener('click', function () {
                var sidebar = document.getElementById('sidebar');
                var content = document.getElementById('content');
                var menuTitle = document.getElementById('menuTitle');
                sidebar.classList.toggle('collapsed');
                content.classList.toggle('collapsed');

                // Hide/Show the menu title
                if (sidebar.classList.contains('collapsed')) {
                    menuTitle.style.display = 'none';
                } else {
                    menuTitle.style.display = 'block';
                }
            });
        });
    </script>
</body>
</html>